# Generated by Django 4.1.2 on 2022-10-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutus_telegram_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, upload_to='projects_covers/')),
            ],
        ),
        migrations.AddField(
            model_name='workexperience',
            name='cover',
            field=models.ImageField(blank=True, upload_to='my_picture/'),
        ),
    ]
